cmake_minimum_required(VERSION 3.2)

if(NOT EXTERNAL_PROJECTS_INCLUDE_PATHS OR
   NOT EXTERNAL_PROJECTS_LIBRARIES)
  if(NOT INSTALL_EXTERNAL_PROJECTS_PREFIX)
    set(INSTALL_EXTERNAL_PROJECTS_PREFIX ${CMAKE_CURRENT_BINARY_DIR})
  endif()

  include(${CMAKE_CURRENT_LIST_DIR}/find_mathutils.cmake)
  include(${CMAKE_CURRENT_LIST_DIR}/find_json11.cmake)

  set(EXTERNAL_PROJECTS_INCLUDE_PATHS
      ${MATHUTILS_INCLUDE_PATH}
      ${JSON11_INCLUDE_PATH})

  set(EXTERNAL_PROJECTS_LIBRARIES
      ${JSON11_LIBRARY})
endif()
